CREATE TABLE IF NOT EXISTS sys_config (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    param_name VARCHAR(100) NOT NULL COMMENT '参数名称',
    param_key VARCHAR(100) NOT NULL COMMENT '参数键名',
    param_value TEXT NOT NULL COMMENT '参数值',
    type CHAR(1) NOT NULL DEFAULT 'N' COMMENT '系统内置（Y是 N否）',
    status CHAR(1) NOT NULL DEFAULT '0' COMMENT '状态（0正常 1停用）',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_param_key (param_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统配置表'; 